config/routes.rb
Rails.application.routes.draw do
  # VERB '/path', to: 'controller#action', as: :prefix
  root to: 'flats#index'
  get '/flats/:id', to: 'flats#show', as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  # before_action

  def index
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
    @images = []
    @flats.count.times do
      @images << open('http://le-wagon-tokyo.herokuapp.com/batches/394/student').read
    end
  end

  # http://localhost:3000/flats/:id'
  # http://localhost:3000/flats/145
  def show
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
    @flat = @flats.find do |flat|
      flat['id'].to_s == params[:id]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1>Flats</h1>
  <ul>
    <% @flats.each_with_index do |flat, index| %>
      <div class="card-trip mb-3">
        <%= image_tag flat['imageUrl'], alt: "alttext" %>
        <div class="card-trip-infos">
          <div>
            <h2><%= flat["name"] %></h2>
            <p>Short description here!</p>
          </div>
          <h2 class="card-trip-pricing"><%= flat["priceCurrency"] %><%= flat["price"] %></h2>
          <%= image_tag @images[index], alt: "alttext", class: "card-trip-user avatar-bordered"%>
        <%= link_to "", flat_path(flat['id']), class: 'card-trip-link' %>
        </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/flats/show.html.erb
<h1><%= @flat['name'] %></h1>

<%= link_to 'Back to flats list' , root_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>